### ISSUE TITLE
How to recreate this configuration using Vite?

### ISSUE THREAD

**Issue by WikKam** [theninthsky/client-side-rendering#4]
Hi! The case study is really insightful and I would love to see similar approach in Vite in action, however, I have not enough time and knowledge to create such config by myself. Is there any chance that some of you might include vite version of this repo? Maybe other build tools would also be beneficial?

**Comment by theninthsky** [comment]
@WikKam Thanks for your interest in this project!

Unfortunately, I have no knowledge of Vite or other bundlers and I doubt that any of them is as configurable as Webpack is (Vite might be an exception).

Please keep in mind that Vite might only benefit you during development, while it will harm you in production build times:
https://storybook.js.org/blog/storybook-performance-from-webpack-to-vite

Nevertheless, I will keep this issue open in hope that someday someone will be able to configure most (if not all) of this project in Vite.

**Comment by theninthsky** [comment]
@WikKam 
The project was migrated to Rspack, which is far superior to anything out there.
Cloudflare Pages now takes 1.5s to build this app. With Webpack it took 12.7s.

#10
